site_name: nice_sql

nav:
  - Home: index.md
  - Query Guide:
    - General Queries: tables_ref.md
    - Specific Grants/Populations: grants.md
  - Examples: nice_sql_examples.ipynb



theme:
  name: "material"
  features:
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          show_docstrings_classes: false
          show_docstring_functions: true
          show_docstring_examples: true
  - mkdocs-jupyter


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
